"""Add assessment_type

Revision ID: 728016e2efef
Revises: b2c3d4e5f6a1
Create Date: 2026-04-21 13:29:11.139487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728016e2efef'
down_revision = 'b2c3d4e5f6a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index('ix_assessments_project_id')
        batch_op.drop_index('ix_assessments_project_status')
        batch_op.drop_index('ix_assessments_share_token')
        batch_op.drop_index('ix_assessments_status')
        batch_op.drop_index('ix_assessments_user_id')
        batch_op.create_unique_constraint(None, ['share_token'])
        batch_op.add_column(sa.Column('assessment_type', sa.String(50), nullable=True, server_default='standard'))
        batch_op.add_column(sa.Column('raw_expert_data', sa.JSON(), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_user_id')

    with op.batch_alter_table('question_responses', schema=None) as batch_op:
        batch_op.drop_index('ix_question_responses_assessment_id')
        batch_op.drop_index('ix_question_responses_question_id')

    with op.batch_alter_table('sdg_scores', schema=None) as batch_op:
        batch_op.drop_index('ix_sdg_scores_assessment_id')
        batch_op.drop_index('ix_sdg_scores_assessment_sdg')
        batch_op.drop_index('ix_sdg_scores_sdg_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_column('raw_expert_data')
        batch_op.drop_column('assessment_type')

    with op.batch_alter_table('sdg_scores', schema=None) as batch_op:
        batch_op.create_index('ix_sdg_scores_sdg_id', ['sdg_id'], unique=False)
        batch_op.create_index('ix_sdg_scores_assessment_sdg', ['assessment_id', 'sdg_id'], unique=False)
        batch_op.create_index('ix_sdg_scores_assessment_id', ['assessment_id'], unique=False)

    with op.batch_alter_table('question_responses', schema=None) as batch_op:
        batch_op.create_index('ix_question_responses_question_id', ['question_id'], unique=False)
        batch_op.create_index('ix_question_responses_assessment_id', ['assessment_id'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('ix_projects_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_assessments_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_assessments_status', ['status'], unique=False)
        batch_op.create_index('ix_assessments_share_token', ['share_token'], unique=True)
        batch_op.create_index('ix_assessments_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index('ix_assessments_project_id', ['project_id'], unique=False)

    # ### end Alembic commands ###
