#!/usr/bin/env python3
"""
excel_to_sql.py
---------------
Reads "Resultado para Formatação.xlsx" (141 UIA project submissions) and
generates supabase/03_import_projects.sql with:

  1. INSERT INTO "user"          — one import user
  2. ALTER TABLE projects        — extension columns (idempotent)
  3. INSERT INTO projects        — 141 rows
  4. INSERT INTO assessments     — one per project
  5. INSERT INTO sdg_scores      — one row per SDG connection (Col R)

Usage:
    pip install openpyxl
    python scripts/excel_to_sql.py

Output:
    supabase/03_import_projects.sql
"""

import os
import re
import sys
from pathlib import Path

try:
    import openpyxl
except ImportError:
    print("ERROR: openpyxl not found. Run: pip install openpyxl")
    sys.exit(1)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).parent.parent
EXCEL_FILE = REPO_ROOT / "Resultado para Formatação.xlsx"
OUTPUT_SQL = REPO_ROOT / "supabase" / "03_import_projects.sql"

IMPORT_EMAIL = "import@uia.archi"
IMPORT_NAME  = "UIA Import"

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

def esc(value) -> str:
    """Escape a value for SQL single-quoted string. Returns NULL for empty."""
    if value is None or str(value).strip() == "":
        return "NULL"
    s = str(value).strip()
    # Escape single quotes
    s = s.replace("'", "''")
    return f"'{s}'"


def esc_bool(value) -> str:
    """Return 'true' or 'false' for a boolean-like cell."""
    if value is None:
        return "false"
    return "true" if str(value).strip().upper() == "X" else "false"


def esc_float(value) -> str:
    """Return a float literal or NULL."""
    if value is None or str(value).strip() == "":
        return "NULL"
    try:
        return str(float(str(value).strip()))
    except ValueError:
        return "NULL"


def year_to_date(value) -> str:
    """Convert a year integer/string to 'YYYY-01-01' or NULL."""
    if value is None or str(value).strip() == "":
        return "NULL"
    try:
        year = int(float(str(value).strip()))
        if 1900 <= year <= 2100:
            return f"'{year}-01-01'"
        return "NULL"
    except ValueError:
        return "NULL"


def parse_sdgs(value) -> list[int]:
    """Parse Col R SDG list like '1; 3; 7; 10; 13' → [1, 3, 7, 10, 13]."""
    if value is None or str(value).strip() == "":
        return []
    parts = re.split(r"[;,\s]+", str(value).strip())
    sdgs = []
    for p in parts:
        p = p.strip()
        if p.isdigit():
            n = int(p)
            if 1 <= n <= 17:
                sdgs.append(n)
    return sorted(set(sdgs))


def cell(row, col_index):
    """Return the value of a cell by 0-based column index."""
    return row[col_index].value if col_index < len(row) else None


# ---------------------------------------------------------------------------
# Load workbook
# ---------------------------------------------------------------------------

if not EXCEL_FILE.exists():
    print(f"ERROR: Excel file not found: {EXCEL_FILE}")
    print("Make sure 'Resultado para Formatação.xlsx' is in the repo root.")
    sys.exit(1)

print(f"Loading: {EXCEL_FILE}")
wb = openpyxl.load_workbook(EXCEL_FILE, data_only=True)
ws = wb["Planilha1"]

rows = list(ws.iter_rows(min_row=2))  # skip header row
print(f"  Rows (excluding header): {len(rows)}")

# ---------------------------------------------------------------------------
# Build SQL output
# ---------------------------------------------------------------------------

lines = []

lines.append("-- =============================================================================")
lines.append("-- 03_import_projects.sql")
lines.append("-- Generated by scripts/excel_to_sql.py")
lines.append("-- Imports 141 UIA project submissions from:")
lines.append("--   'Resultado para Formatação.xlsx'")
lines.append("-- =============================================================================")
lines.append("")

# ---------------------------------------------------------------------------
# Step 1 — Create import user
# ---------------------------------------------------------------------------
lines.append("-- ---------------------------------------------------------------------------")
lines.append("-- Step 1: Create import user")
lines.append("-- ---------------------------------------------------------------------------")
lines.append("")
lines.append("INSERT INTO \"user\" (name, email, password_hash, is_admin)")
lines.append(f"VALUES ({esc(IMPORT_NAME)}, {esc(IMPORT_EMAIL)}, 'not-a-real-hash', true)")
lines.append("ON CONFLICT (email) DO NOTHING;")
lines.append("")

# ---------------------------------------------------------------------------
# Step 2 — Extension columns (idempotent guard)
# ---------------------------------------------------------------------------
lines.append("-- ---------------------------------------------------------------------------")
lines.append("-- Step 2: Add extension columns (idempotent — already in 01_schema.sql)")
lines.append("-- ---------------------------------------------------------------------------")
lines.append("")
lines.append("ALTER TABLE projects")
lines.append("    ADD COLUMN IF NOT EXISTS external_code VARCHAR(16),")
lines.append("    ADD COLUMN IF NOT EXISTS authors       TEXT,")
lines.append("    ADD COLUMN IF NOT EXISTS organization  VARCHAR(255),")
lines.append("    ADD COLUMN IF NOT EXISTS uia_region    VARCHAR(64),")
lines.append("    ADD COLUMN IF NOT EXISTS selected      BOOLEAN DEFAULT false;")
lines.append("")

# ---------------------------------------------------------------------------
# Step 3 — Insert projects
# ---------------------------------------------------------------------------
lines.append("-- ---------------------------------------------------------------------------")
lines.append("-- Step 3: Insert projects (141 rows)")
lines.append("-- ---------------------------------------------------------------------------")
lines.append("")

project_rows_info = []  # [(external_code, sdg_list), ...]

for i, row in enumerate(rows, start=1):
    # Column map (0-based index A=0, B=1, ..., Z=25)
    selected_flag = esc_bool(cell(row, 0))   # A
    # B = SDG primary (col 1) — not used directly; Col R has the full list
    code          = cell(row, 2)              # C
    # D = sequential int (col 3) — skip
    name          = cell(row, 4)              # E
    authors_val   = cell(row, 5)              # F
    org_val       = cell(row, 6)              # G
    region_val    = cell(row, 7)              # H
    # I = client (col 8) — skipped per plan
    location_val  = cell(row, 9)              # J
    # K = geographic ref (col 10) — skip
    size_val      = cell(row, 11)             # L
    year_val      = cell(row, 12)             # M
    # N = empty (col 13) — skip
    desc_val      = cell(row, 14)             # O  (200-char description)
    summary_val   = cell(row, 15)             # P  (500-char summary)
    # Q = SDG explanation (col 16) — skip for now
    sdg_list_val  = cell(row, 17)             # R  (SDG connections)
    # S–Z = contact info — skip

    # Skip completely empty rows
    if name is None and code is None:
        continue

    # Build combined description
    desc_parts = []
    if desc_val and str(desc_val).strip():
        desc_parts.append(str(desc_val).strip())
    if summary_val and str(summary_val).strip():
        desc_parts.append(str(summary_val).strip())
    combined_desc = " ".join(desc_parts) if desc_parts else None

    sdgs = parse_sdgs(sdg_list_val)
    ext_code = str(code).strip() if code else f"ROW{i}"
    project_rows_info.append((ext_code, sdgs))

    lines.append(f"-- Row {i}: {ext_code}")
    lines.append("INSERT INTO projects (")
    lines.append("    name, description, location, size_sqm, end_date,")
    lines.append("    status, project_type, sector,")
    lines.append("    user_id,")
    lines.append("    external_code, authors, organization, uia_region, selected,")
    lines.append("    created_at")
    lines.append(") VALUES (")
    lines.append(f"    {esc(name)},")
    lines.append(f"    {esc(combined_desc)},")
    lines.append(f"    {esc(location_val)},")
    lines.append(f"    {esc_float(size_val)},")
    lines.append(f"    {year_to_date(year_val)},")
    lines.append(f"    'completed', 'architectural', 'public',")
    lines.append(f"    (SELECT id FROM \"user\" WHERE email = {esc(IMPORT_EMAIL)}),")
    lines.append(f"    {esc(ext_code)}, {esc(authors_val)}, {esc(org_val)}, {esc(region_val)}, {selected_flag},")
    lines.append(f"    NOW()")
    lines.append(");")
    lines.append("")

# ---------------------------------------------------------------------------
# Step 4 — Create assessments
# ---------------------------------------------------------------------------
lines.append("-- ---------------------------------------------------------------------------")
lines.append("-- Step 4: Create assessments (one per project)")
lines.append("-- ---------------------------------------------------------------------------")
lines.append("")
lines.append("INSERT INTO assessments (")
lines.append("    project_id, user_id, status, assessment_type,")
lines.append("    step1_completed, created_at")
lines.append(")")
lines.append("SELECT")
lines.append("    p.id,")
lines.append(f"    (SELECT id FROM \"user\" WHERE email = {esc(IMPORT_EMAIL)}),")
lines.append("    'completed',")
lines.append("    'standard',")
lines.append("    true,")
lines.append("    NOW()")
lines.append("FROM projects p")
lines.append("WHERE p.external_code IS NOT NULL")
lines.append("  AND p.user_id = (SELECT id FROM \"user\" WHERE email = " + esc(IMPORT_EMAIL) + ");")
lines.append("")

# ---------------------------------------------------------------------------
# Step 5 — Seed sdg_scores from Col R
# ---------------------------------------------------------------------------
lines.append("-- ---------------------------------------------------------------------------")
lines.append("-- Step 5: Seed sdg_scores from Col R SDG connection lists")
lines.append("-- NULL scores — no questionnaire data available")
lines.append("-- ---------------------------------------------------------------------------")
lines.append("")

for ext_code, sdgs in project_rows_info:
    if not sdgs:
        continue
    sdg_array = ", ".join(str(s) for s in sdgs)
    lines.append(f"-- {ext_code}: SDGs {sdg_array}")
    lines.append("INSERT INTO sdg_scores (assessment_id, sdg_id, created_at)")
    lines.append("SELECT a.id, g.id, NOW()")
    lines.append("FROM assessments a")
    lines.append("JOIN projects p ON p.id = a.project_id")
    lines.append(f"JOIN sdg_goals g ON g.number = ANY(ARRAY[{sdg_array}]::int[])")
    lines.append(f"WHERE p.external_code = {esc(ext_code)}")
    lines.append(f"  AND p.user_id = (SELECT id FROM \"user\" WHERE email = {esc(IMPORT_EMAIL)});")
    lines.append("")

# ---------------------------------------------------------------------------
# Verification queries (commented out)
# ---------------------------------------------------------------------------
lines.append("-- ---------------------------------------------------------------------------")
lines.append("-- Verification (run manually after import):")
lines.append("-- ---------------------------------------------------------------------------")
lines.append("-- SELECT COUNT(*) FROM projects;                    -- expect 141")
lines.append("-- SELECT COUNT(*) FROM assessments;                 -- expect 141")
lines.append("-- SELECT COUNT(*) FROM sdg_scores;                  -- varies by SDG connections")
lines.append("-- SELECT p.name, p.external_code, p.location")
lines.append("--   FROM projects p WHERE p.external_code = 'EFP1';")
lines.append("")

# ---------------------------------------------------------------------------
# Write output
# ---------------------------------------------------------------------------
output = "\n".join(lines)
OUTPUT_SQL.parent.mkdir(parents=True, exist_ok=True)
OUTPUT_SQL.write_text(output, encoding="utf-8")

print(f"\nGenerated: {OUTPUT_SQL}")
print(f"  Projects to insert:  {len(project_rows_info)}")
total_sdg_pairs = sum(len(sdgs) for _, sdgs in project_rows_info)
print(f"  SDG score rows:      {total_sdg_pairs}")
print(f"  Output file size:    {OUTPUT_SQL.stat().st_size:,} bytes")
print("\nDone. Run supabase/03_import_projects.sql in the Supabase SQL Editor.")
